create table people
(
    id         integer primary key,
    name       TEXT,
    age        INTEGER,
    location   TEXT,
    occupation TEXT,
    email      TEXT
);

insert into people (id, name, age, location, occupation, email)
values  (1, 'Christopher Sharp', 63, 'Los Angeles, CA', 'Paediatric nurse', 'grantanderson@simmons-jackson.com'),
        (2, 'Sharon Fernandez', 69, 'San Diego, CA', 'Cabin crew', 'christysanders@white-love.net'),
        (3, 'Rachel Thornton', 76, 'San Jose, CA', 'Engineer, electrical', 'douglas57@hotmail.com'),
        (4, 'Richard Moore', 90, 'San Jose, CA', 'Audiological scientist', 'myersdaniel@williams-gutierrez.org'),
        (5, 'Kevin Fletcher', 22, 'San Jose, CA', 'Barrister''s clerk', 'hjohnson@hotmail.com'),
        (6, 'John Beasley', 57, 'San Jose, CA', 'Product/process development scientist', 'thompsonpamela@gmail.com'),
        (7, 'Luis Anderson', 88, 'San Antonio, TX', 'Engineer, biomedical', 'phale@gmail.com'),
        (8, 'Barbara Hodges', 84, 'Dallas, TX', 'Amenity horticulturist', 'maciaskatherine@knight.com'),
        (9, 'Carla Weber', 95, 'Chicago, IL', 'Community pharmacist', 'amycampbell@stanley.info'),
        (10, 'Sarah Little', 75, 'Chicago, IL', 'Horticultural consultant', 'jenniferbrown@carroll.org'),
        (11, 'Jessica Greer', 93, 'San Antonio, TX', 'Engineer, broadcasting (operations)', 'xnelson@day-williams.com'),
        (12, 'Brent Arnold', 27, 'San Antonio, TX', 'Lobbyist', 'pjacobs@hotmail.com'),
        (13, 'Natalie Trujillo', 59, 'Houston, TX', 'Dramatherapist', 'john40@ashley.com'),
        (14, 'Megan Gonzalez', 87, 'Houston, TX', 'Education officer, community', 'jacqueline01@hotmail.com'),
        (15, 'Steven Davila', 60, 'Dallas, TX', 'Psychiatrist', 'denisedominguez@hotmail.com'),
        (16, 'Joseph Parker', 44, 'Los Angeles, CA', 'Scientist, product/process development', 'mendozamatthew@yahoo.com'),
        (17, 'Jennifer Travis', 56, 'Dallas, TX', 'Automotive engineer', 'hbaker@gmail.com'),
        (18, 'Mr. Kenneth Phillips DVM', 81, 'Dallas, TX', 'Community arts worker', 'kmorton@gmail.com'),
        (19, 'Dean Moore', 98, 'Dallas, TX', 'Engineer, site', 'bushdenise@gmail.com'),
        (20, 'Dr. Margaret Ford', 94, 'Philadelphia, PA', 'Stage manager', 'mclarke@hotmail.com'),
        (21, 'Jennifer Morrow', 65, 'San Antonio, TX', 'Best boy', 'marshallrobert@hotmail.com'),
        (22, 'Robert Rivera', 45, 'San Antonio, TX', 'Call centre manager', 'isaac50@russell-wagner.info'),
        (23, 'Tammy Powell', 72, 'San Antonio, TX', 'Editor, commissioning', 'wsmith@hotmail.com'),
        (24, 'John Hughes', 81, 'Phoenix, AZ', 'Holiday representative', 'cameron72@wright.info'),
        (25, 'Mary Smith', 50, 'Phoenix, AZ', 'Location manager', 'bergdennis@yahoo.com'),
        (26, 'Laurie Burke', 79, 'San Antonio, TX', 'Event organiser', 'steven32@yahoo.com'),
        (27, 'Kevin Smith', 49, 'Dallas, TX', 'Accommodation manager', 'boydhannah@yahoo.com'),
        (28, 'John Foster', 80, 'Houston, TX', 'Field seismologist', 'garrettmartin@dixon.com'),
        (29, 'Ashlee Charles', 63, 'San Jose, CA', 'Editor, commissioning', 'rholmes@vega.info'),
        (30, 'Cynthia Potts', 34, 'New York, NY', 'Lecturer, higher education', 'ulang@vasquez.org'),
        (31, 'Jesus Brady', 61, 'Dallas, TX', 'Forensic scientist', 'gonzalezbrenda@gmail.com'),
        (32, 'Jamie Smith', 59, 'Philadelphia, PA', 'Retail buyer', 'taylorthomas@soto.com'),
        (33, 'Abigail Hicks', 34, 'Chicago, IL', 'Therapist, speech and language', 'lori49@gmail.com'),
        (34, 'Thomas Rodriguez', 63, 'San Jose, CA', 'Retail banker', 'erica79@glover-forbes.com'),
        (35, 'Eric Wilkinson', 75, 'San Antonio, TX', 'Art gallery manager', 'pnixon@callahan.com'),
        (36, 'Matthew Cantu', 39, 'Los Angeles, CA', 'Chief Financial Officer', 'reynoldsgregory@gmail.com'),
        (37, 'Chloe Chapman', 35, 'Philadelphia, PA', 'Production manager', 'bdavis@hotmail.com'),
        (38, 'Sophia Jones', 48, 'San Jose, CA', 'Camera operator', 'gsantos@gmail.com'),
        (39, 'David Young', 56, 'Houston, TX', 'Psychologist, clinical', 'leslie55@hotmail.com'),
        (40, 'Stacy Morris', 72, 'Los Angeles, CA', 'Logistics and distribution manager', 'qhansen@yahoo.com'),
        (41, 'Julie Lin', 56, 'Los Angeles, CA', 'Social worker', 'gzimmerman@gmail.com'),
        (42, 'Melinda White', 92, 'Philadelphia, PA', 'Probation officer', 'pamela45@yahoo.com'),
        (43, 'Elizabeth Daniel', 95, 'Dallas, TX', 'Sports coach', 'lauriegriffin@fletcher-garcia.com'),
        (44, 'Stephanie Fuller', 86, 'San Antonio, TX', 'Heritage manager', 'benjamin88@gmail.com'),
        (45, 'Peter Salinas', 32, 'Philadelphia, PA', 'Building control surveyor', 'charles57@martin-lane.com'),
        (46, 'Michael Hart', 83, 'Dallas, TX', 'Purchasing manager', 'john23@hotmail.com'),
        (47, 'Roger Oconnor', 75, 'Chicago, IL', 'Arts administrator', 'heather19@yahoo.com'),
        (48, 'John Stanley', 25, 'San Jose, CA', 'Training and development officer', 'kyle24@gmail.com'),
        (49, 'William Hatfield', 39, 'Los Angeles, CA', 'Adult guidance worker', 'ajohnson@hoover.net'),
        (50, 'Brent Stout', 72, 'San Diego, CA', 'Fish farm manager', 'marcus27@richardson-jones.com'),
        (51, 'Mitchell Jackson', 66, 'New York, NY', 'Quantity surveyor', 'nclark@hotmail.com'),
        (52, 'Jake Davila', 28, 'San Diego, CA', 'Quality manager', 'victorcastro@yahoo.com'),
        (53, 'Doris Hodge', 72, 'San Antonio, TX', 'Computer games developer', 'watersscott@hotmail.com'),
        (54, 'Erica Harris', 88, 'San Diego, CA', 'Secondary school teacher', 'achurch@burton-mejia.com'),
        (55, 'Joseph Hansen', 59, 'Dallas, TX', 'Medical secretary', 'olsenricardo@yahoo.com'),
        (56, 'Barbara Stout', 72, 'San Jose, CA', 'Clinical biochemist', 'victoriabrewer@allen.com'),
        (57, 'Sandra Gonzalez', 73, 'Chicago, IL', 'Engineer, maintenance', 'james02@snyder.com'),
        (58, 'Matthew Jones', 43, 'Philadelphia, PA', 'Electronics engineer', 'craigperez@moore.biz'),
        (59, 'Terry Nichols', 93, 'Philadelphia, PA', 'Outdoor activities/education manager', 'rogersnicole@chang-stanley.com'),
        (60, 'James Berry', 94, 'San Jose, CA', 'Buyer, industrial', 'serranochristopher@harrison-williams.org'),
        (61, 'Angela Sandoval', 71, 'Phoenix, AZ', 'Optician, dispensing', 'hurleyjennifer@williams.org'),
        (62, 'John Hawkins', 38, 'San Antonio, TX', 'Programmer, systems', 'johnsondonna@miller.com'),
        (63, 'Thomas Cooper', 45, 'San Antonio, TX', 'Advertising art director', 'gonzalezjeffrey@nelson-reynolds.com'),
        (64, 'Olivia Owens', 86, 'San Diego, CA', 'Buyer, retail', 'robertsontyler@edwards-hansen.com'),
        (65, 'Kelli Rodriguez', 34, 'Philadelphia, PA', 'Therapist, horticultural', 'tara21@gmail.com'),
        (66, 'Jeanette Briggs', 61, 'Philadelphia, PA', 'Tourism officer', 'alexander42@jones.com'),
        (67, 'Kimberly Perry', 71, 'Dallas, TX', 'Firefighter', 'conwaymichelle@duran.org'),
        (68, 'Jorge Brandt', 74, 'Phoenix, AZ', 'Programmer, systems', 'veronicafigueroa@weber-johnson.com'),
        (69, 'Brent Hayes', 71, 'New York, NY', 'Conservator, furniture', 'sgallagher@cook-marshall.net'),
        (70, 'Julie Blake', 99, 'San Diego, CA', 'Colour technologist', 'chriswilson@hawkins.com'),
        (71, 'David Jackson MD', 33, 'New York, NY', 'Arts administrator', 'melissa67@davila-johnson.com'),
        (72, 'Anna Nunez', 28, 'Dallas, TX', 'Plant breeder/geneticist', 'lhernandez@rodriguez.org'),
        (73, 'Caleb Adams', 38, 'San Diego, CA', 'Podiatrist', 'ugonzales@mitchell-lopez.info'),
        (74, 'Morgan Haas', 88, 'San Jose, CA', 'Toxicologist', 'michael10@yahoo.com'),
        (75, 'Emily Baker', 22, 'Phoenix, AZ', 'Equities trader', 'bherring@hotmail.com'),
        (76, 'Madison Edwards', 33, 'Houston, TX', 'Field seismologist', 'shawn27@webb.com'),
        (77, 'Edwin Conley', 63, 'San Jose, CA', 'Communications engineer', 'christinatapia@mendez-hughes.com'),
        (78, 'Meredith Randall', 57, 'Los Angeles, CA', 'Exercise physiologist', 'andrewneal@yahoo.com'),
        (79, 'George Ramos', 95, 'New York, NY', 'Energy engineer', 'charles02@hotmail.com'),
        (80, 'Harry Watts', 77, 'San Diego, CA', 'Copywriter, advertising', 'david08@warner.com'),
        (81, 'Lisa Lee', 77, 'Philadelphia, PA', 'Tourism officer', 'alishapratt@gmail.com'),
        (82, 'John Watson', 19, 'Houston, TX', 'Chief Executive Officer', 'robynhernandez@gmail.com'),
        (83, 'Joseph Sanchez', 20, 'Chicago, IL', 'Phytotherapist', 'allisonlauren@mcintyre.com'),
        (84, 'Seth Young', 18, 'Chicago, IL', 'Economist', 'elizabethbrown@hall-heath.com'),
        (85, 'Luis Gentry', 55, 'Houston, TX', 'Technical author', 'cpowers@williams.org'),
        (86, 'Dawn Jones', 39, 'Dallas, TX', 'Designer, television/film set', 'amber85@jackson-lee.com'),
        (87, 'David Davila', 81, 'Los Angeles, CA', 'Adult nurse', 'melissawilson@cantrell-reyes.org'),
        (88, 'Amy Donaldson', 49, 'San Diego, CA', 'Computer games developer', 'abigailgomez@gmail.com'),
        (89, 'Christine Burke', 84, 'Philadelphia, PA', 'Energy manager', 'obrown@smith-mckinney.org'),
        (90, 'Krista Gordon', 83, 'Chicago, IL', 'Computer games developer', 'kelleynicole@grant.com'),
        (91, 'Vanessa Gibson', 67, 'Chicago, IL', 'Armed forces operational officer', 'nicholasreid@wright-jones.com'),
        (92, 'Wendy Palmer', 47, 'Houston, TX', 'Engineer, maintenance (IT)', 'ymeyer@hotmail.com'),
        (93, 'Alicia Bass', 86, 'Houston, TX', 'Applications developer', 'joneslinda@adams-conley.com'),
        (94, 'Jason Lyons', 33, 'Philadelphia, PA', 'Newspaper journalist', 'kimberlysharp@ballard.info'),
        (95, 'Travis Cohen', 98, 'San Antonio, TX', 'Music tutor', 'drakejohn@castro.info'),
        (96, 'Miss Regina Bullock', 72, 'Houston, TX', 'Fisheries officer', 'amymercer@hotmail.com'),
        (97, 'Kevin Johnson', 80, 'San Antonio, TX', 'Futures trader', 'sampsonkimberly@hotmail.com'),
        (98, 'Mark Bailey', 66, 'San Jose, CA', 'Programmer, applications', 'nanderson@west-barajas.com'),
        (99, 'Dustin Clark', 91, 'Dallas, TX', 'Teacher, early years/pre', 'barrettjohn@miller.com'),
        (100, 'Autumn Reed', 29, 'Phoenix, AZ', 'Ophthalmologist', 'hannah08@hotmail.com');
